//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.08 at 05:14:56 PM IST 
//


package com.sp3.mvc.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardinfoid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardnum" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="nameoncard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="cardtype">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DEBITCARD"/>
 *               &lt;enumeration value="CREDITCARD"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cardgatewaytype">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="VISA"/>
 *               &lt;enumeration value="MASTERCARD"/>
 *               &lt;enumeration value="AMEX"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cardcvvnum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardinfoid",
    "cardnum",
    "nameoncard",
    "expdate",
    "cardtype",
    "cardgatewaytype",
    "cardcvvnum"
})
@XmlRootElement(name = "cardinfo", namespace = "Cardinfo")
public class Cardinfo {

    @XmlElement(required = true)
    protected String cardinfoid;
    @XmlElement(required = true)
    protected BigInteger cardnum;
    @XmlElement(required = true)
    protected String nameoncard;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expdate;
    @XmlElement(required = true)
    protected String cardtype;
    @XmlElement(required = true)
    protected String cardgatewaytype;
    protected int cardcvvnum;

    /**
     * Gets the value of the cardinfoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardinfoid() {
        return cardinfoid;
    }

    /**
     * Sets the value of the cardinfoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardinfoid(String value) {
        this.cardinfoid = value;
    }

    /**
     * Gets the value of the cardnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardnum() {
        return cardnum;
    }

    /**
     * Sets the value of the cardnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardnum(BigInteger value) {
        this.cardnum = value;
    }

    /**
     * Gets the value of the nameoncard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameoncard() {
        return nameoncard;
    }

    /**
     * Sets the value of the nameoncard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameoncard(String value) {
        this.nameoncard = value;
    }

    /**
     * Gets the value of the expdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpdate() {
        return expdate;
    }

    /**
     * Sets the value of the expdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpdate(XMLGregorianCalendar value) {
        this.expdate = value;
    }

    /**
     * Gets the value of the cardtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * Sets the value of the cardtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardtype(String value) {
        this.cardtype = value;
    }

    /**
     * Gets the value of the cardgatewaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardgatewaytype() {
        return cardgatewaytype;
    }

    /**
     * Sets the value of the cardgatewaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardgatewaytype(String value) {
        this.cardgatewaytype = value;
    }

    /**
     * Gets the value of the cardcvvnum property.
     * 
     */
    public int getCardcvvnum() {
        return cardcvvnum;
    }

    /**
     * Sets the value of the cardcvvnum property.
     * 
     */
    public void setCardcvvnum(int value) {
        this.cardcvvnum = value;
    }

}
