//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.08 at 05:14:56 PM IST 
//


package com.sp3.mvc.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debtid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accholdername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accnum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="acctype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankbranch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ifsccode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="debtamount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="debtdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="debtfrequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="debtstatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DEBITED"/>
 *               &lt;enumeration value="PENDING"/>
 *               &lt;enumeration value="FAILURE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "debtid",
    "accholdername",
    "accnum",
    "acctype",
    "bankname",
    "bankbranch",
    "ifsccode",
    "debtamount",
    "debtdate",
    "debtfrequency",
    "debtstatus"
})
@XmlRootElement(name = "directdebit", namespace = "DirectDebit")
public class Directdebit {

    @XmlElement(required = true)
    protected String debtid;
    @XmlElement(required = true)
    protected String accholdername;
    protected int accnum;
    @XmlElement(required = true)
    protected String acctype;
    @XmlElement(required = true)
    protected String bankname;
    @XmlElement(required = true)
    protected String bankbranch;
    @XmlElement(required = true)
    protected String ifsccode;
    protected double debtamount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar debtdate;
    @XmlElement(required = true)
    protected String debtfrequency;
    @XmlElement(required = true)
    protected String debtstatus;

    /**
     * Gets the value of the debtid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtid() {
        return debtid;
    }

    /**
     * Sets the value of the debtid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtid(String value) {
        this.debtid = value;
    }

    /**
     * Gets the value of the accholdername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccholdername() {
        return accholdername;
    }

    /**
     * Sets the value of the accholdername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccholdername(String value) {
        this.accholdername = value;
    }

    /**
     * Gets the value of the accnum property.
     * 
     */
    public int getAccnum() {
        return accnum;
    }

    /**
     * Sets the value of the accnum property.
     * 
     */
    public void setAccnum(int value) {
        this.accnum = value;
    }

    /**
     * Gets the value of the acctype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctype() {
        return acctype;
    }

    /**
     * Sets the value of the acctype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctype(String value) {
        this.acctype = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankname(String value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the bankbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankbranch() {
        return bankbranch;
    }

    /**
     * Sets the value of the bankbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankbranch(String value) {
        this.bankbranch = value;
    }

    /**
     * Gets the value of the ifsccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfsccode() {
        return ifsccode;
    }

    /**
     * Sets the value of the ifsccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfsccode(String value) {
        this.ifsccode = value;
    }

    /**
     * Gets the value of the debtamount property.
     * 
     */
    public double getDebtamount() {
        return debtamount;
    }

    /**
     * Sets the value of the debtamount property.
     * 
     */
    public void setDebtamount(double value) {
        this.debtamount = value;
    }

    /**
     * Gets the value of the debtdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDebtdate() {
        return debtdate;
    }

    /**
     * Sets the value of the debtdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDebtdate(XMLGregorianCalendar value) {
        this.debtdate = value;
    }

    /**
     * Gets the value of the debtfrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtfrequency() {
        return debtfrequency;
    }

    /**
     * Sets the value of the debtfrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtfrequency(String value) {
        this.debtfrequency = value;
    }

    /**
     * Gets the value of the debtstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtstatus() {
        return debtstatus;
    }

    /**
     * Sets the value of the debtstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtstatus(String value) {
        this.debtstatus = value;
    }

}
