//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.08 at 05:14:56 PM IST 
//


package com.sp3.mvc.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{Cardinfo}cardinfo"/>
 *         &lt;element ref="{DirectDebit}directdebit"/>
 *         &lt;element name="transactionid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transamount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="transdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="transtype">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DebitCard"/>
 *               &lt;enumeration value="CreditCard"/>
 *               &lt;enumeration value="NetBanking"/>
 *               &lt;enumeration value="ECS"/>
 *               &lt;enumeration value="CashOnDelivery"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardinfo",
    "directdebit",
    "transactionid",
    "paymentid",
    "transamount",
    "transdate",
    "transtype"
})
@XmlRootElement(name = "transaction", namespace = "Transaction")
public class Transaction {

    @XmlElement(namespace = "Cardinfo", required = true)
    protected Cardinfo cardinfo;
    @XmlElement(namespace = "DirectDebit", required = true)
    protected Directdebit directdebit;
    @XmlElement(required = true)
    protected String transactionid;
    @XmlElement(required = true)
    protected String paymentid;
    protected double transamount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar transdate;
    @XmlElement(required = true)
    protected String transtype;

    /**
     * Gets the value of the cardinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Cardinfo }
     *     
     */
    public Cardinfo getCardinfo() {
        return cardinfo;
    }

    /**
     * Sets the value of the cardinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cardinfo }
     *     
     */
    public void setCardinfo(Cardinfo value) {
        this.cardinfo = value;
    }

    /**
     * Gets the value of the directdebit property.
     * 
     * @return
     *     possible object is
     *     {@link Directdebit }
     *     
     */
    public Directdebit getDirectdebit() {
        return directdebit;
    }

    /**
     * Sets the value of the directdebit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directdebit }
     *     
     */
    public void setDirectdebit(Directdebit value) {
        this.directdebit = value;
    }

    /**
     * Gets the value of the transactionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionid() {
        return transactionid;
    }

    /**
     * Sets the value of the transactionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionid(String value) {
        this.transactionid = value;
    }

    /**
     * Gets the value of the paymentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentid() {
        return paymentid;
    }

    /**
     * Sets the value of the paymentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentid(String value) {
        this.paymentid = value;
    }

    /**
     * Gets the value of the transamount property.
     * 
     */
    public double getTransamount() {
        return transamount;
    }

    /**
     * Sets the value of the transamount property.
     * 
     */
    public void setTransamount(double value) {
        this.transamount = value;
    }

    /**
     * Gets the value of the transdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransdate() {
        return transdate;
    }

    /**
     * Sets the value of the transdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransdate(XMLGregorianCalendar value) {
        this.transdate = value;
    }

    /**
     * Gets the value of the transtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranstype() {
        return transtype;
    }

    /**
     * Sets the value of the transtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranstype(String value) {
        this.transtype = value;
    }

}
