//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 03:45:41 PM IST 
//


package com.sop.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{Request}orderitem"/>
 *         &lt;element name="orderstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderitem",
    "orderstatus"
})
@XmlRootElement(name = "OrderItemProcessRequest")
public class OrderItemProcessRequest {

    @XmlElement(required = true)
    protected Orderitem orderitem;
    @XmlElement(required = true)
    protected String orderstatus;

    /**
     * Gets the value of the orderitem property.
     * 
     * @return
     *     possible object is
     *     {@link Orderitem }
     *     
     */
    public Orderitem getOrderitem() {
        return orderitem;
    }

    /**
     * Sets the value of the orderitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orderitem }
     *     
     */
    public void setOrderitem(Orderitem value) {
        this.orderitem = value;
    }

    /**
     * Gets the value of the orderstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * Sets the value of the orderstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderstatus(String value) {
        this.orderstatus = value;
    }

}
