//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 03:45:41 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "Request", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sop.request;
